---
title: "Aim 1 - Differential Expression Analysis"
output:
html_notebook: default
---

```{r, echo=FALSE, message=FALSE, warning=FALSE}

library(GEOquery)
library(limma)
library(tidyverse)
library(readxl)
library(pheatmap)
library(affy)
library(annotate)
library(RColorBrewer)
library(hgu133plus2.db)
library(hgu133plus2cdf)
library(here)
library(dendsort)
library(ggrepel)

if (!dir.exists(here('data/diff_exp_output'))) {
  dir.create(here('data/diff_exp_output'))
}
if (!dir.exists(here('figs'))) {
  dir.create(here('figs'))
}
```

# DEA Functions

```{r}
run_diffexp_analysis <- function(expr_data, design_matrix, probe_to_gene, save=T, out_dir=NA, dataset_name=NA) {
  # get top differentially expressed genes
  fit <- lmFit(expr_data, design_matrix)
  fit_ebayes <- eBayes(fit)
  diffexp_df <- topTable(fit_ebayes, sort.by='logFC', number=Inf) |>
    rownames_to_column(var='probe_id') |>
    inner_join(probe_to_gene, by=c('probe_id'))
  
  out_fname <- paste(dataset_name, '.csv', sep='')
  if (save) write.csv(diffexp_df, paste(out_dir, out_fname, sep=''))
  
  return (diffexp_df)
}

filter_diffexp_results <- function(diffexp_df, fc_thresh, p_thresh, save=T, out_dir=NA, dataset_name=NA) {
  # filter down to genes with log FC and p-value above/below thresholds
  diffexp_filt_df <- diffexp_df |>
    filter((abs(logFC) > fc_thresh & adj.P.Val < p_thresh))
  
  out_fname_suffix <- sprintf('fc-%.2f_p-%.2f.csv', fc_thresh, p_thresh)
  out_fname <- paste(dataset_name, out_fname_suffix, sep='_')
  if (save) write.csv(diffexp_filt_df, paste(out_dir, out_fname, sep=''))
  
  return (diffexp_filt_df)
}

get_top_gene_names <- function(diffexp_df, fc_thresh, p_thresh, n=150, direction='upreg', 
                               save=T, out_dir=NA, dataset_name=NA) {
  diffexp_filt_df <- filter_diffexp_results(diffexp_df, fc_thresh, p_thresh, save=F) 
  
  if (direction == 'upreg') {
    top_gene_names <- diffexp_filt_df |>
      filter(logFC > 0) |>
      slice_max(logFC, n=n) |>
      dplyr::select(gene_symbol)
  } else {
    top_gene_names <- diffexp_filt_df |>
      filter(logFC < 0) |>
      slice_min(logFC, n=n) |>
      dplyr::select(gene_symbol)
  }
  out_fname_suffix <- sprintf('fc-%.2f_p-%.2f_%s-%d.csv', fc_thresh, p_thresh, direction, n)
  out_fname <- paste(dataset_name, out_fname_suffix, sep='_')
  write.table(top_gene_names, 
              paste(out_dir, out_fname, sep=''),
              row.names=FALSE,
              col.names=FALSE,
              quote=FALSE)
  
  return(top_gene_names)
}

plot_heatmap <- function(expr_data_input, data_lbls, save_fname) {
  # hierarchically cluster just the top genes
  dists <- dist(t(expr_data_input))
  dists_mat <- as.matrix(dists)
  max_dist <- max(dists_mat)
  min_dist <- min(dists_mat)
  dists_mat <- (max_dist - dists_mat) / (max_dist - min_dist)
  
  colors <- colorRampPalette(rev(brewer.pal(9, "Blues")) )(255)
  
  annot_df <- data.frame(Group = factor(data_lbls,
                                      levels=c(0, 1),
                                      labels=c("control", "disease")))
  rownames(annot_df) <- rownames(dists_mat)
  
  grp_colors <- c("darkseagreen", "goldenrod1")
  names(grp_colors) <- c("control", "disease")
  annot_colors <- list(Group = grp_colors)
  
  p <- pheatmap(dists_mat,
                clustering_distance_rows = dists,
                clustering_distance_cols = dists,
                color = colors,
                annotation_col = annot_df,
                annotation_colors=annot_colors,
                annotation_names_col=F,
                show_rownames=F,
                show_colnames=F,
                cellheight=1,
                cellwidth=1,
                filename = save_fname)
}
```

# GSE141549 (Gabriel) DEA

```{r, echo=FALSE}
# load data from GEO
gabriel_geo <- getGEO('GSE141549')
gabriel_geo_plat1 <- gabriel_geo[[1]]
gabriel_geo_plat1[['disease stage:ch1']] <- as.integer(gabriel_geo_plat1[['disease stage:ch1']] != "Healthy")
gabriel_geo_plat2 <- gabriel_geo[[2]]
gabriel_geo_plat2[['disease stage:ch1']] <- as.integer(gabriel_geo_plat2[['disease stage:ch1']] != "Healthy")


# for some reason, the above load doesn't include expression data,
# so have to manually download from NCI website 
# downloaded from here https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE141549
gabriel_expr_data <- read_excel(here('data/diff_exp_input/GSE141549_batchCorrectednormalizedArrayscombined.xlsx'))
```

```{r}
# get sample phenotypes (endometriosis vs non-endometriosis)
gabriel_plat1_lbls <- pData(gabriel_geo_plat1) |> 
  dplyr::select(title, `disease stage:ch1`) |>
  drop_na(`disease stage:ch1`)
gabriel_plat2_lbls <- pData(gabriel_geo_plat2) |> 
  dplyr::select(title, `disease stage:ch1`) |>
  drop_na(`disease stage:ch1`)
gabriel_lbls <- bind_rows(gabriel_plat1_lbls, gabriel_plat2_lbls) |> arrange(title)

print(sprintf('controls = %d', sum(gabriel_lbls == 0)))
print(sprintf('patients = %d', sum(gabriel_lbls == 1)))

gabriel_design <- model.matrix( ~gabriel_lbls[['disease stage:ch1']])

gabriel_expr_data_input <- gabriel_expr_data |> 
  column_to_rownames(var="Probe_Id") |>
  dplyr::select(gabriel_lbls$title)

gabriel_probe_to_gene <- gabriel_expr_data |>
  dplyr::select(Probe_Id, Gene_symbol) |>
  dplyr::rename(gene_symbol = Gene_symbol, probe_id = Probe_Id) 
```

```{r}
# hierarchically cluster expression data to see if there's normal/disease separation
gabriel_heatmap_fname <- here('figs/GSE141549_expr_heatmap.png')
plot_heatmap(gabriel_expr_data_input, gabriel_lbls[['disease stage:ch1']], gabriel_heatmap_fname)
```

```{r}
# run differential expression analysis on GSE141549
gabriel_diffexp_df <- run_diffexp_analysis(gabriel_expr_data_input, gabriel_design, gabriel_probe_to_gene,
                                           out_dir='../data/diff_exp_output/', dataset_name='GSE141549')
gabriel_diffexp_filt_df <- filter_diffexp_results(gabriel_diffexp_df, fc_thresh=0.5, p_thresh=0.05,
                                                  out_dir='../data/diff_exp_output/', dataset_name='GSE141549')
gabriel_top150_ureg_genes <- get_top_gene_names(gabriel_diffexp_df, fc_thresh=0.5, p_thresh=0.05, direction='upreg', n=150,
                                                out_dir='../data/diff_exp_output/', dataset_name='GSE141549')
gabriel_top150_dreg_genes <- get_top_gene_names(gabriel_diffexp_df, fc_thresh=0.5, p_thresh=0.05, direction='downreg', n=150,
                                                out_dir='../data/diff_exp_output/', dataset_name='GSE141549')

```

```{r}
# hierarchically cluster just the top genes
gabriel_expr_data_top <- gabriel_expr_data_input |>
  filter(rownames(gabriel_expr_data_input) %in% gabriel_diffexp_filt_df$probe_id)
gabriel_top_heatmap_fname <- here('figs/GSE141549_top_expr_heatmap.png')
plot_heatmap(gabriel_expr_data_top, gabriel_lbls[['disease stage:ch1']], gabriel_top_heatmap_fname)
```

```{r}

```

# GSE51981 (Tamaresis) DEA

```{r}
# load preprocessed data from GEO 
tamaresis_geo <- getGEO('GSE51981')
tamaresis_geo_plat1 <- tamaresis_geo[[1]]
tamaresis_geo_plat1[["endometriosis/no endometriosis:ch1"]] <-
  as.integer(tamaresis_geo_plat1[["endometriosis/no endometriosis:ch1"]] == "Endometriosis")

```

```{r}
# extract sample phenotypes (endometriosis vs non-endometriosis)
tamaresis_lbls <- pData(tamaresis_geo_plat1) |> 
  dplyr::select(geo_accession, `endometriosis/no endometriosis:ch1`) |>
  drop_na(`endometriosis/no endometriosis:ch1`)

print(sprintf('controls = %d', sum(tamaresis_lbls == 0)))
print(sprintf('patients = %d', sum(tamaresis_lbls == 1)))

tamaresis_design <- model.matrix( ~tamaresis_lbls[['endometriosis/no endometriosis:ch1']])

# extract expression data
tamaresis_expr_data_input <- as.data.frame(exprs(tamaresis_geo_plat1)) |>
  dplyr::select(tamaresis_lbls$geo_accession)

tamaresis_probe_to_gene <- select(hgu133plus2.db, 
                                  rownames(tamaresis_expr_data_input), 
                                  c('SYMBOL')) |> 
  dplyr::rename(gene_symbol = SYMBOL, probe_id = PROBEID)
```

```{r}
# hierarchically cluster expression data to see if there's normal/disease separation
tamaresis_heatmap_fname <- here('figs/GS51981_expr_heatmap.png')
plot_heatmap(tamaresis_expr_data_input, tamaresis_lbls[['endometriosis/no endometriosis:ch1']], tamaresis_heatmap_fname)
```

```{r}
# run differential expression analysis on GSE51981
tamaresis_diffexp_df <- run_diffexp_analysis(tamaresis_expr_data_input, tamaresis_design, tamaresis_probe_to_gene,
                                           out_dir='../data/diff_exp_output/', dataset_name='GSE51981')
tamaresis_diffexp_filt_df <- filter_diffexp_results(tamaresis_diffexp_df, fc_thresh=0.5, p_thresh=0.05,
                                                  out_dir='../data/diff_exp_output/', dataset_name='GSE51981')
tamaresis_top150_ureg_genes <- get_top_gene_names(tamaresis_diffexp_df, fc_thresh=0.5, p_thresh=0.05,
                                                  direction='upreg', n=150,
                                                  out_dir='../data/diff_exp_output/', dataset_name='GSE51981')
tamaresis_top150_dreg_genes <- get_top_gene_names(tamaresis_diffexp_df, fc_thresh=0.5, p_thresh=0.05,
                                                  direction='downreg', n=150,
                                                  out_dir='../data/diff_exp_output/', dataset_name='GSE51981')
```

```{r}
# hierarchically cluster just the top genes
tamaresis_expr_data_top <- tamaresis_expr_data_input |>
  filter(rownames(tamaresis_expr_data_input) %in% tamaresis_diffexp_filt_df$probe_id)
tamaresis_top_heatmap_fname <- here('figs/GS51981_top_expr_heatmap.png')
plot_heatmap(tamaresis_expr_data_top, tamaresis_lbls[['endometriosis/no endometriosis:ch1']], tamaresis_top_heatmap_fname)
```

# Plot correlation matrices

```{r}
gabriel_diffexp_df <- gabriel_diffexp_df |>
  mutate(diffexpr = case_when(
     (logFC >= 0.5 & adj.P.Val < 0.05) ~ 'up',
     (logFC <= -0.5 & adj.P.Val < 0.05) ~ 'down',
     TRUE ~ 'none'
  ))
ggplot(gabriel_diffexp_df, aes(x=logFC, y=-log10(adj.P.Val), color=diffexpr)) + 
  scale_color_manual(values=c("blue", "gray", "red")) +
  geom_point(size=1, show.legend=FALSE) + 
  theme_minimal() +
  ggtitle('GSE141549')

ggsave(here('figs/GSE141549_volcano.png'))
```

# Make volcano plots

```{r}
gabriel_diffexp_df$dataset_name <- 'GSE141549'
tamaresis_diffexp_df$dataset_name <- 'GSE51981'

diffexp_df <- bind_rows(gabriel_diffexp_df, tamaresis_diffexp_df)
extreme_up <- diffexp_df |>
  group_by(dataset_name) |>
  slice_max(n=5, logFC) |>
  mutate(label = gene_symbol) |>
  ungroup() |>
  dplyr::select(dataset_name, logFC, gene_symbol, label)
extreme_down <- diffexp_df |>
  group_by(dataset_name) |>
  slice_min(n=5, logFC) |>
  mutate(label = gene_symbol) |>
  ungroup() |>
  dplyr::select(dataset_name, logFC, gene_symbol, label)

extreme <- bind_rows(extreme_up, extreme_down)


diffexp_df <- diffexp_df |>
  mutate(
    diffexpr = case_when(
      (logFC >= 0.5 & adj.P.Val < 0.05) ~ 'up',
      (logFC <= -0.5 & adj.P.Val < 0.05) ~ 'down',
      TRUE ~ 'none')) |>
  left_join(extreme, by=c('dataset_name'='dataset_name', 'logFC' = 'logFC', 'gene_symbol'='gene_symbol')) 

ggplot(diffexp_df, aes(x=logFC, y=-log10(adj.P.Val), color=diffexpr, label=label)) + 
  scale_color_manual(values=c("blue", "gray", "red")) +
  geom_point(size=1, show.legend=FALSE, alpha=0.5) + 
  theme_minimal() +
  geom_text_repel(color='black', size=4) +
  geom_vline(xintercept=c(-0.5, 0.5), col="black", linetype='dashed') +
  geom_hline(yintercept=-log10(0.05), col="black", linetype='dashed') +
  facet_wrap(vars(dataset_name)) 

ggsave(here('figs/combined_volcano.png'))
```

# Sanity Checking - Concordance in Differentially Expressed Genes

```{r}
# load top genes from Oskotsky paper 
oskotsky_diffexp_df <- as.data.frame(read_excel('../data/diff_exp_input/oskotsky.xlsx', sheet="DvC_unstratified")) |>
  mutate(logFC = -`logFC (Control/Disease)`)

oskotsky_top150_ureg_genes <- get_top_gene_names(oskotsky_diffexp_df, fc_thresh=0.5, p_thresh=0.05,
                                                  direction='upreg', n=150,
                                                  out_dir='../data/diff_exp_output/', dataset_name='oskotsky')
oskotsky_top150_dreg_genes <- get_top_gene_names(tamaresis_diffexp_df, fc_thresh=0.5, p_thresh=0.05,
                                                  direction='downreg', n=150,
                                                  out_dir='../data/diff_exp_output/', dataset_name='oskotsky')
```

```{r}
# examine intersecting genes 
intersect(gabriel_top150_ureg_genes$gene_symbol, tamaresis_top150_ureg_genes$gene_symbol)
intersect(gabriel_top150_dreg_genes$gene_symbol, tamaresis_top150_dreg_genes$gene_symbol)
```

```{r}
length(intersect(gabriel_top150_ureg_genes$gene_symbol, oskotsky_top150_ureg_genes$gene_symbol))
length(intersect(tamaresis_top150_ureg_genes$gene_symbol, oskotsky_top150_ureg_genes$gene_symbol))
length(intersect(gabriel_top150_ureg_genes$gene_symbol, tamaresis_top150_ureg_genes$gene_symbol))

length(intersect(gabriel_top150_dreg_genes$gene_symbol, oskotsky_top150_dreg_genes$gene_symbol))
length(intersect(tamaresis_top150_dreg_genes$gene_symbol, oskotsky_top150_dreg_genes$gene_symbol))
length(intersect(gabriel_top150_dreg_genes$gene_symbol, tamaresis_top150_dreg_genes$gene_symbol))
```
